package de.dhbw.modellbahn.parser.lexer;

public enum TokenType {
    EOF,
    ADD_KEYWORD,
    AT_KEYWORD,
    TO_KEYWORD,
    FACING_KEYWORD,
    USING_KEYWORD,
    DRIVE_COMMAND,
    CONSIDER_KEYWORD,
    MODIFY_KEYWORD,
    LIST_KEYWORD,
    TOGGLE_KEYWORD,
    DIRECTION_KEYWORD,
    POSITION_KEYWORD,
    LOCOMOTIVES_KEYWORD,
    GRAPHPOINTS_KEYWORD,
    SYSTEM_KEYWORD,
    START_KEYWORD,
    STOP_KEYWORD,
    SPEED_KEYWORD,
    NEW_KEYWORD,
    ROUTE_KEYWORD,
    WITH_KEYWORD,
    REMOVE_KEYWORD,
    AUTOMATIC_KEYWORD,

    HEIGHT_KEYWORD,
    ELECTRIFICATION_KEYWORD,

    OPTIMIZATION,
    ROUTING_OPTION,
    COMMENT,

    NUMBER,
    STRING,
    ALGORITHM,
    AWAIT_KEYWORD, TIMEOUT_KEYWORD, IF_KEYWORD, THEN_KEYWORD, ELSE_KEYWORD, ENDIF_KEYWORD, BOOLEAN
}
