package de.dhbw.modellbahn.plugin.parser.lexer;

public enum TokenType {
    EOF,
    ADD_KEYWORD,
    AT_KEYWORD,
    TO_KEYWORD,
    FACING_KEYWORD,
    USING_KEYWORD,
    DRIVE_COMMAND,
    CONSIDER_KEYWORD,

    HEIGHT_KEYWORD,
    ELECTRIFICATION_KEYWORD,

    OPTIMIZATION,
    LOC_ID,
    ROUTING_OPTION,
    COMMENT,
    MODIFY_KEYWORD,
    LIST_KEYWORD,
    TOGGLE_KEYWORD,
    DIRECTION_KEYWORD,
    POSITION_KEYWORD,
    LOCOMOTIVES_KEYWORD,
    GRAPHPOINTS_KEYWORD,
    SYSTEM_KEYWORD,
    START_KEYWORD,
    STOP_KEYWORD,
    GRAPH_POINT
}
