- name: W1
  id1: 12289 # left way
  id2: 12288 # right way
  root: W4
  straight: K2
  left: K9
  right: W12

- name: W5
  id1: 12292 # left way
  id2: 12295 # right way
  root: K31
  straight: K21
  left: K17
  right: K10