/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.moba.communication.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * AccessoryDecoderSwitchingTimeCommand
 */
@JsonPropertyOrder({
        AccessoryDecoderSwitchingTimeCommand.JSON_PROPERTY_HASH_VALUE,
        AccessoryDecoderSwitchingTimeCommand.JSON_PROPERTY_RESPONSE,
        AccessoryDecoderSwitchingTimeCommand.JSON_PROPERTY_ID,
        AccessoryDecoderSwitchingTimeCommand.JSON_PROPERTY_TIME
})
public class AccessoryDecoderSwitchingTimeCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_TIME = "time";
    private Integer hashValue;
    private Boolean response;
    private Integer id;
    private Integer time;

    public AccessoryDecoderSwitchingTimeCommand() {
    }

    public AccessoryDecoderSwitchingTimeCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public AccessoryDecoderSwitchingTimeCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public AccessoryDecoderSwitchingTimeCommand id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(Integer id) {
        this.id = id;
    }


    public AccessoryDecoderSwitchingTimeCommand time(Integer time) {
        this.time = time;
        return this;
    }

    /**
     * Get time
     *
     * @return time
     */
    @JsonProperty(JSON_PROPERTY_TIME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getTime() {
        return time;
    }


    @JsonProperty(JSON_PROPERTY_TIME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTime(Integer time) {
        this.time = time;
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, id, time);
    }

    /**
     * Return true if this AccessoryDecoderSwitchingTimeCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccessoryDecoderSwitchingTimeCommand accessoryDecoderSwitchingTimeCommand = (AccessoryDecoderSwitchingTimeCommand) o;
        return Objects.equals(this.hashValue, accessoryDecoderSwitchingTimeCommand.hashValue) &&
                Objects.equals(this.response, accessoryDecoderSwitchingTimeCommand.response) &&
                Objects.equals(this.id, accessoryDecoderSwitchingTimeCommand.id) &&
                Objects.equals(this.time, accessoryDecoderSwitchingTimeCommand.time);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AccessoryDecoderSwitchingTimeCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    time: ").append(toIndentedString(time)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

