/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.moba.communication.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum DCCProgramming {

    DIRECT_PROGRAMMING("DirectProgramming"),

    REGISTER_PROGRAMMING("RegisterProgramming"),

    BIT_PROGRAMMING("BitProgramming");

    private String value;

    DCCProgramming(String value) {
        this.value = value;
    }

    @JsonCreator
    public static DCCProgramming fromValue(String value) {
        for (DCCProgramming b : DCCProgramming.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

}

