/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.moba.communication.dto;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum ProtocolSchema {

    MFX("MFX"),

    MM2_20("MM2_20"),

    MM2_40("MM2_40"),

    DCC_READ_SHORT("DCC_read_short"),

    DCC_READ_LONG("DCC_read_long"),

    DCC_IDENTIFY("DCC_identify"),

    SX1_READ("SX1_read"),

    SX1_IDENTIFY("SX1_identify"),

    MFX_MAIN("MFX_main");

    private String value;

    ProtocolSchema(String value) {
        this.value = value;
    }

    @JsonCreator
    public static ProtocolSchema fromValue(String value) {
        for (ProtocolSchema b : ProtocolSchema.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

}

