/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.moba.communication.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum RailProtocolSchema {

    MM2_2040("MM2_2040"),

    MM2_20("MM2_20"),

    MM2_40("MM2_40"),

    DCC_SHORT_28("DCC_short_28"),

    DCC_SHORT_14("DCC_short_14"),

    DCC_SHORT_126("DCC_short_126"),

    DCC_LONG_28("DCC_long_28"),

    DCC_LONG_126("DCC_long_126");

    private String value;

    RailProtocolSchema(String value) {
        this.value = value;
    }

    @JsonCreator
    public static RailProtocolSchema fromValue(String value) {
        for (RailProtocolSchema b : RailProtocolSchema.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

}

