/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.moba.communication.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * ServiceStatusDataConfigurationCommand
 */
@JsonPropertyOrder({
        ServiceStatusDataConfigurationCommand.JSON_PROPERTY_HASH_VALUE,
        ServiceStatusDataConfigurationCommand.JSON_PROPERTY_RESPONSE,
        ServiceStatusDataConfigurationCommand.JSON_PROPERTY_DEVICE_ID,
        ServiceStatusDataConfigurationCommand.JSON_PROPERTY_INDEX,
        ServiceStatusDataConfigurationCommand.JSON_PROPERTY_COUNT,
        ServiceStatusDataConfigurationCommand.JSON_PROPERTY_DATA
})
public class ServiceStatusDataConfigurationCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_DEVICE_ID = "device_id";
    public static final String JSON_PROPERTY_INDEX = "index";
    public static final String JSON_PROPERTY_COUNT = "count";
    public static final String JSON_PROPERTY_DATA = "data";
    private Integer hashValue;
    private Boolean response;
    private Integer deviceId;
    private Integer index;
    private Integer count;
    private String data;

    public ServiceStatusDataConfigurationCommand() {
    }

    public ServiceStatusDataConfigurationCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public ServiceStatusDataConfigurationCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public ServiceStatusDataConfigurationCommand deviceId(Integer deviceId) {
        this.deviceId = deviceId;
        return this;
    }

    /**
     * Get deviceId
     *
     * @return deviceId
     */
    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getDeviceId() {
        return deviceId;
    }


    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }


    public ServiceStatusDataConfigurationCommand index(Integer index) {
        this.index = index;
        return this;
    }

    /**
     * Get index
     *
     * @return index
     */
    @JsonProperty(JSON_PROPERTY_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getIndex() {
        return index;
    }


    @JsonProperty(JSON_PROPERTY_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIndex(Integer index) {
        this.index = index;
    }


    public ServiceStatusDataConfigurationCommand count(Integer count) {
        this.count = count;
        return this;
    }

    /**
     * Get count
     *
     * @return count
     */
    @JsonProperty(JSON_PROPERTY_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getCount() {
        return count;
    }


    @JsonProperty(JSON_PROPERTY_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCount(Integer count) {
        this.count = count;
    }


    public ServiceStatusDataConfigurationCommand data(String data) {
        this.data = data;
        return this;
    }

    /**
     * Get data
     *
     * @return data
     */
    @JsonProperty(JSON_PROPERTY_DATA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getData() {
        return data;
    }


    @JsonProperty(JSON_PROPERTY_DATA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setData(String data) {
        this.data = data;
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, deviceId, index, count, data);
    }

    /**
     * Return true if this ServiceStatusDataConfigurationCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ServiceStatusDataConfigurationCommand serviceStatusDataConfigurationCommand = (ServiceStatusDataConfigurationCommand) o;
        return Objects.equals(this.hashValue, serviceStatusDataConfigurationCommand.hashValue) &&
                Objects.equals(this.response, serviceStatusDataConfigurationCommand.response) &&
                Objects.equals(this.deviceId, serviceStatusDataConfigurationCommand.deviceId) &&
                Objects.equals(this.index, serviceStatusDataConfigurationCommand.index) &&
                Objects.equals(this.count, serviceStatusDataConfigurationCommand.count) &&
                Objects.equals(this.data, serviceStatusDataConfigurationCommand.data);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ServiceStatusDataConfigurationCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
        sb.append("    index: ").append(toIndentedString(index)).append("\n");
        sb.append("    count: ").append(toIndentedString(count)).append("\n");
        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

