/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.moba.communication.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * SystemStatusCommand
 */
@JsonPropertyOrder({
        SystemStatusCommand.JSON_PROPERTY_HASH_VALUE,
        SystemStatusCommand.JSON_PROPERTY_RESPONSE,
        SystemStatusCommand.JSON_PROPERTY_ID,
        SystemStatusCommand.JSON_PROPERTY_CHANNEL,
        SystemStatusCommand.JSON_PROPERTY_MEASURED_VALUE
})
public class SystemStatusCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_CHANNEL = "channel";
    public static final String JSON_PROPERTY_MEASURED_VALUE = "measured_value";
    private Integer hashValue;
    private Boolean response;
    private Integer id;
    private Integer channel;
    private Integer measuredValue;

    public SystemStatusCommand() {
    }

    public SystemStatusCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public SystemStatusCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public SystemStatusCommand id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(Integer id) {
        this.id = id;
    }


    public SystemStatusCommand channel(Integer channel) {
        this.channel = channel;
        return this;
    }

    /**
     * Get channel
     *
     * @return channel
     */
    @JsonProperty(JSON_PROPERTY_CHANNEL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getChannel() {
        return channel;
    }


    @JsonProperty(JSON_PROPERTY_CHANNEL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setChannel(Integer channel) {
        this.channel = channel;
    }


    public SystemStatusCommand measuredValue(Integer measuredValue) {
        this.measuredValue = measuredValue;
        return this;
    }

    /**
     * Get measuredValue
     *
     * @return measuredValue
     */
    @JsonProperty(JSON_PROPERTY_MEASURED_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getMeasuredValue() {
        return measuredValue;
    }


    @JsonProperty(JSON_PROPERTY_MEASURED_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMeasuredValue(Integer measuredValue) {
        this.measuredValue = measuredValue;
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, id, channel, measuredValue);
    }

    /**
     * Return true if this SystemStatusCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SystemStatusCommand systemStatusCommand = (SystemStatusCommand) o;
        return Objects.equals(this.hashValue, systemStatusCommand.hashValue) &&
                Objects.equals(this.response, systemStatusCommand.response) &&
                Objects.equals(this.id, systemStatusCommand.id) &&
                Objects.equals(this.channel, systemStatusCommand.channel) &&
                Objects.equals(this.measuredValue, systemStatusCommand.measuredValue);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SystemStatusCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
        sb.append("    measuredValue: ").append(toIndentedString(measuredValue)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

