/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.moba.communication.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * WriteConfigControlByte
 */
@JsonPropertyOrder({
        WriteConfigControlByte.JSON_PROPERTY_IS_MAIN,
        WriteConfigControlByte.JSON_PROPERTY_IS_MULTI_BYTE,
        WriteConfigControlByte.JSON_PROPERTY_DCC_PROGRAMMING
})
public class WriteConfigControlByte {
    public static final String JSON_PROPERTY_IS_MAIN = "is_main";
    public static final String JSON_PROPERTY_IS_MULTI_BYTE = "is_multi_byte";
    public static final String JSON_PROPERTY_DCC_PROGRAMMING = "dcc_programming";
    private Boolean isMain;
    private Boolean isMultiByte;
    private DCCProgramming dccProgramming;

    public WriteConfigControlByte() {
    }

    public WriteConfigControlByte(Boolean isMain, Boolean isMultiByte, DCCProgramming dccProgramming) {
        this.isMain = isMain;
        this.isMultiByte = isMultiByte;
        this.dccProgramming = dccProgramming;
    }

    public WriteConfigControlByte isMain(Boolean isMain) {
        this.isMain = isMain;
        return this;
    }

    /**
     * Get isMain
     *
     * @return isMain
     */
    @JsonProperty(JSON_PROPERTY_IS_MAIN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getIsMain() {
        return isMain;
    }


    @JsonProperty(JSON_PROPERTY_IS_MAIN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setIsMain(Boolean isMain) {
        this.isMain = isMain;
    }


    public WriteConfigControlByte isMultiByte(Boolean isMultiByte) {
        this.isMultiByte = isMultiByte;
        return this;
    }

    /**
     * Get isMultiByte
     *
     * @return isMultiByte
     */
    @JsonProperty(JSON_PROPERTY_IS_MULTI_BYTE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getIsMultiByte() {
        return isMultiByte;
    }


    @JsonProperty(JSON_PROPERTY_IS_MULTI_BYTE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setIsMultiByte(Boolean isMultiByte) {
        this.isMultiByte = isMultiByte;
    }


    public WriteConfigControlByte dccProgramming(DCCProgramming dccProgramming) {
        this.dccProgramming = dccProgramming;
        return this;
    }

    /**
     * Get dccProgramming
     *
     * @return dccProgramming
     */
    @JsonProperty(JSON_PROPERTY_DCC_PROGRAMMING)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public DCCProgramming getDccProgramming() {
        return dccProgramming;
    }


    @JsonProperty(JSON_PROPERTY_DCC_PROGRAMMING)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDccProgramming(DCCProgramming dccProgramming) {
        this.dccProgramming = dccProgramming;
    }

    @Override
    public int hashCode() {
        return Objects.hash(isMain, isMultiByte, dccProgramming);
    }

    /**
     * Return true if this WriteConfigControlByte object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WriteConfigControlByte writeConfigControlByte = (WriteConfigControlByte) o;
        return Objects.equals(this.isMain, writeConfigControlByte.isMain) &&
                Objects.equals(this.isMultiByte, writeConfigControlByte.isMultiByte) &&
                Objects.equals(this.dccProgramming, writeConfigControlByte.dccProgramming);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class WriteConfigControlByte {\n");
        sb.append("    isMain: ").append(toIndentedString(isMain)).append("\n");
        sb.append("    isMultiByte: ").append(toIndentedString(isMultiByte)).append("\n");
        sb.append("    dccProgramming: ").append(toIndentedString(dccProgramming)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

