/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.moba.communication.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * WriteConfigCommand
 */
@JsonPropertyOrder({
        WriteConfigCommand.JSON_PROPERTY_HASH_VALUE,
        WriteConfigCommand.JSON_PROPERTY_RESPONSE,
        WriteConfigCommand.JSON_PROPERTY_LOC_ID,
        WriteConfigCommand.JSON_PROPERTY_INDEX,
        WriteConfigCommand.JSON_PROPERTY_NUMBER,
        WriteConfigCommand.JSON_PROPERTY_VALUE,
        WriteConfigCommand.JSON_PROPERTY_CONTROL,
        WriteConfigCommand.JSON_PROPERTY_RESULT
})
public class WriteConfigCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_LOC_ID = "loc_id";
    public static final String JSON_PROPERTY_INDEX = "index";
    public static final String JSON_PROPERTY_NUMBER = "number";
    public static final String JSON_PROPERTY_VALUE = "value";
    public static final String JSON_PROPERTY_CONTROL = "control";
    public static final String JSON_PROPERTY_RESULT = "result";
    private Integer hashValue;
    private Boolean response;
    private Integer locId;
    private Integer index;
    private Integer number;
    private Integer value;
    private WriteConfigControlByte control;
    private WriteConfigResultByte result;

    public WriteConfigCommand() {
    }

    public WriteConfigCommand(Integer hashValue, Boolean response, Integer locId, Integer index, Integer number, Integer value, WriteConfigControlByte control, WriteConfigResultByte result) {
        this.hashValue = hashValue;
        this.response = response;
        this.locId = locId;
        this.index = index;
        this.number = number;
        this.value = value;
        this.control = control;
        this.result = result;
    }

    public WriteConfigCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public WriteConfigCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public WriteConfigCommand locId(Integer locId) {
        this.locId = locId;
        return this;
    }

    /**
     * Get locId
     *
     * @return locId
     */
    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getLocId() {
        return locId;
    }


    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLocId(Integer locId) {
        this.locId = locId;
    }


    public WriteConfigCommand index(Integer index) {
        this.index = index;
        return this;
    }

    /**
     * Get index
     *
     * @return index
     */
    @JsonProperty(JSON_PROPERTY_INDEX)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getIndex() {
        return index;
    }


    @JsonProperty(JSON_PROPERTY_INDEX)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setIndex(Integer index) {
        this.index = index;
    }


    public WriteConfigCommand number(Integer number) {
        this.number = number;
        return this;
    }

    /**
     * Get number
     *
     * @return number
     */
    @JsonProperty(JSON_PROPERTY_NUMBER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getNumber() {
        return number;
    }


    @JsonProperty(JSON_PROPERTY_NUMBER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNumber(Integer number) {
        this.number = number;
    }


    public WriteConfigCommand value(Integer value) {
        this.value = value;
        return this;
    }

    /**
     * Get value
     *
     * @return value
     */
    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getValue() {
        return value;
    }


    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setValue(Integer value) {
        this.value = value;
    }


    public WriteConfigCommand control(WriteConfigControlByte control) {
        this.control = control;
        return this;
    }

    /**
     * Get control
     *
     * @return control
     */
    @JsonProperty(JSON_PROPERTY_CONTROL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public WriteConfigControlByte getControl() {
        return control;
    }


    @JsonProperty(JSON_PROPERTY_CONTROL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setControl(WriteConfigControlByte control) {
        this.control = control;
    }


    public WriteConfigCommand result(WriteConfigResultByte result) {
        this.result = result;
        return this;
    }

    /**
     * Get result
     *
     * @return result
     */
    @JsonProperty(JSON_PROPERTY_RESULT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public WriteConfigResultByte getResult() {
        return result;
    }


    @JsonProperty(JSON_PROPERTY_RESULT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setResult(WriteConfigResultByte result) {
        this.result = result;
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, locId, index, number, value, control, result);
    }

    /**
     * Return true if this WriteConfigCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WriteConfigCommand writeConfigCommand = (WriteConfigCommand) o;
        return Objects.equals(this.hashValue, writeConfigCommand.hashValue) &&
                Objects.equals(this.response, writeConfigCommand.response) &&
                Objects.equals(this.locId, writeConfigCommand.locId) &&
                Objects.equals(this.index, writeConfigCommand.index) &&
                Objects.equals(this.number, writeConfigCommand.number) &&
                Objects.equals(this.value, writeConfigCommand.value) &&
                Objects.equals(this.control, writeConfigCommand.control) &&
                Objects.equals(this.result, writeConfigCommand.result);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class WriteConfigCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    locId: ").append(toIndentedString(locId)).append("\n");
        sb.append("    index: ").append(toIndentedString(index)).append("\n");
        sb.append("    number: ").append(toIndentedString(number)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    control: ").append(toIndentedString(control)).append("\n");
        sb.append("    result: ").append(toIndentedString(result)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

