- id: 16389
  name: 95 0041-4 DR
  # Default values
  maxSpeed: 1.0 # in mm/ms
  accelerationTime: 1000 # in ms
  accelerationDistance: 200 # in mm
  decelerationDistance: 200 # in mm
  position: W17
  facingDirection: B

- id: 16390
  name: 6310 Crossrail
  # Default values
  maxSpeed: 1.0
  accelerationTime: 1000
  accelerationDistance: 200
  decelerationDistance: 200
  position: A
  facingDirection: B

- id: 16391
  name: 260 319-9 DB
  # Default values
  maxSpeed: 1.0
  accelerationTime: 1000
  accelerationDistance: 200
  decelerationDistance: 200
  position: A
  facingDirection: B

- id: 16392
  name: 96 024 DRG
  # Default values
  maxSpeed: 1.0
  accelerationTime: 1000
  accelerationDistance: 200
  decelerationDistance: 200
  position: A
  facingDirection: B

- id: 16397
  name: 150 144-4 DB AG
  # Default values
  maxSpeed: 1.0
  accelerationTime: 1000
  accelerationDistance: 200
  decelerationDistance: 200
  position: A
  facingDirection: B

- id: 16398
  name: Fc 2x3/4 122 01
  # Default values
  maxSpeed: 1.0
  accelerationTime: 1000
  accelerationDistance: 200
  decelerationDistance: 200
  position: A
  facingDirection: B