---
- id: 16389
  name: "95 0041-4 DR"
  electric: false
  maxSpeed: 0.392
  accelerationTime: 10533
  accelerationDistance: 1650
  decelerationTime: 10533
  decelerationDistance: 1650
  position: "NotOnTrack"
  facingDirection: "NotOnTrack"
- id: 16390
  name: "6310 Crossrail"
  electric: false
  maxSpeed: 0.492
  accelerationTime: 5079
  accelerationDistance: 1052
  decelerationTime: 5079
  decelerationDistance: 1052
  position: "NotOnTrack"
  facingDirection: "NotOnTrack"
- id: 16391
  name: "260 319-9 DB"
  electric: false
  maxSpeed: 0.401
  accelerationTime: 2244
  accelerationDistance: 335
  decelerationTime: 2244
  decelerationDistance: 335
  position: "NotOnTrack"
  facingDirection: "NotOnTrack"
- id: 16392
  name: "96 024 DRG"
  electric: false
  maxSpeed: 0.317
  accelerationTime: 8512
  accelerationDistance: 1048
  decelerationTime: 8512
  decelerationDistance: 1048
  position: "NotOnTrack"
  facingDirection: "NotOnTrack"
- id: 16397
  name: "150 144-4 DB AG"
  electric: true
  maxSpeed: 0.59
  accelerationTime: 2960
  accelerationDistance: 713
  decelerationTime: 2960
  decelerationDistance: 713
  position: "NotOnTrack"
  facingDirection: "NotOnTrack"
- id: 16398
  name: "Fc 2x3/4 122 01"
  electric: true
  maxSpeed: 0.234
  accelerationTime: 4576
  accelerationDistance: 458
  decelerationTime: 4576
  decelerationDistance: 458
  position: "NotOnTrack"
  facingDirection: "NotOnTrack"
