- id: 16389
  name: 95 0041-4 DR
  # Default values
  maxSpeed: 1.0 # in mm/ms
  accelerationTime: 1000 # in ms
  accelerationDistance: 200 # in mm
  decelerationTime: 1000 # in ms
  decelerationDistance: 200 # in mm
  position: W17
  facingDirection: B

- id: 16390
  name: 6310 Crossrail
  # Default values
  maxSpeed: 1.0
  accelerationTime: 1000
  accelerationDistance: 200
  decelerationTime: 1000
  decelerationDistance: 200
  position: W17
  facingDirection: B

- id: 16391
  name: 260 319-9 DB
  # Default values
  maxSpeed: 0.401
  accelerationTime: 2244
  accelerationDistance: 335
  decelerationTime: 2244
  decelerationDistance: 335
  position: K16
  facingDirection: W15

- id: 16392
  name: 96 024 DRG
  # Default values
  maxSpeed: 1.0
  accelerationTime: 1000
  accelerationDistance: 200
  decelerationTime: 1000
  decelerationDistance: 200
  position: A
  facingDirection: B

- id: 16397
  name: 150 144-4 DB AG
  # Default values
  maxSpeed: 0.59645
  accelerationTime: 2960
  accelerationDistance: 713
  decelerationTime: 2960
  decelerationDistance: 713
  position: W15
  facingDirection: K7

- id: 16398
  name: Fc 2x3/4 122 01
  # Default values
  maxSpeed: 1.0
  accelerationTime: 1000
  accelerationDistance: 200
  decelerationTime: 1000
  decelerationDistance: 200
  position: A
  facingDirection: B