/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * EnableRailProtocolCommand
 */
@JsonPropertyOrder({
        EnableRailProtocolCommand.JSON_PROPERTY_HASH_VALUE,
        EnableRailProtocolCommand.JSON_PROPERTY_RESPONSE,
        EnableRailProtocolCommand.JSON_PROPERTY_ID,
        EnableRailProtocolCommand.JSON_PROPERTY_BITSET
})
public class EnableRailProtocolCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_BITSET = "bitset";
    private Integer hashValue;
    private Boolean response;
    private Integer id;
    private Integer bitset;

    public EnableRailProtocolCommand() {
    }

    public EnableRailProtocolCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public EnableRailProtocolCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public EnableRailProtocolCommand id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(Integer id) {
        this.id = id;
    }


    public EnableRailProtocolCommand bitset(Integer bitset) {
        this.bitset = bitset;
        return this;
    }

    /**
     * Get bitset
     *
     * @return bitset
     */
    @JsonProperty(JSON_PROPERTY_BITSET)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getBitset() {
        return bitset;
    }


    @JsonProperty(JSON_PROPERTY_BITSET)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setBitset(Integer bitset) {
        this.bitset = bitset;
    }


    /**
     * Return true if this EnableRailProtocolCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EnableRailProtocolCommand enableRailProtocolCommand = (EnableRailProtocolCommand) o;
        return Objects.equals(this.hashValue, enableRailProtocolCommand.hashValue) &&
                Objects.equals(this.response, enableRailProtocolCommand.response) &&
                Objects.equals(this.id, enableRailProtocolCommand.id) &&
                Objects.equals(this.bitset, enableRailProtocolCommand.bitset);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, id, bitset);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EnableRailProtocolCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    bitset: ").append(toIndentedString(bitset)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

