/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * LocomotiveFunctionCommand
 */
@JsonPropertyOrder({
        LocomotiveFunctionCommand.JSON_PROPERTY_HASH_VALUE,
        LocomotiveFunctionCommand.JSON_PROPERTY_RESPONSE,
        LocomotiveFunctionCommand.JSON_PROPERTY_LOC_ID,
        LocomotiveFunctionCommand.JSON_PROPERTY_FUNCTION,
        LocomotiveFunctionCommand.JSON_PROPERTY_VALUE,
        LocomotiveFunctionCommand.JSON_PROPERTY_FUNCTION_VALUE
})
public class LocomotiveFunctionCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_LOC_ID = "loc_id";
    public static final String JSON_PROPERTY_FUNCTION = "function";
    public static final String JSON_PROPERTY_VALUE = "value";
    public static final String JSON_PROPERTY_FUNCTION_VALUE = "function_value";
    private Integer hashValue;
    private Boolean response;
    private Integer locId;
    private Integer function;
    private Integer value;
    private Integer functionValue;

    public LocomotiveFunctionCommand() {
    }

    public LocomotiveFunctionCommand(Integer hashValue, Boolean response, Integer locId, Integer function, Integer value, Integer functionValue) {
        this.hashValue = hashValue;
        this.response = response;
        this.locId = locId;
        this.function = function;
        this.value = value;
        this.functionValue = functionValue;
    }

    public LocomotiveFunctionCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public LocomotiveFunctionCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public LocomotiveFunctionCommand locId(Integer locId) {
        this.locId = locId;
        return this;
    }

    /**
     * Get locId
     *
     * @return locId
     */
    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getLocId() {
        return locId;
    }


    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLocId(Integer locId) {
        this.locId = locId;
    }


    public LocomotiveFunctionCommand function(Integer function) {
        this.function = function;
        return this;
    }

    /**
     * Get function
     *
     * @return function
     */
    @JsonProperty(JSON_PROPERTY_FUNCTION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getFunction() {
        return function;
    }


    @JsonProperty(JSON_PROPERTY_FUNCTION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setFunction(Integer function) {
        this.function = function;
    }


    public LocomotiveFunctionCommand value(Integer value) {
        this.value = value;
        return this;
    }

    /**
     * Get value
     *
     * @return value
     */
    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getValue() {
        return value;
    }


    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setValue(Integer value) {
        this.value = value;
    }


    public LocomotiveFunctionCommand functionValue(Integer functionValue) {
        this.functionValue = functionValue;
        return this;
    }

    /**
     * Get functionValue
     *
     * @return functionValue
     */
    @JsonProperty(JSON_PROPERTY_FUNCTION_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getFunctionValue() {
        return functionValue;
    }


    @JsonProperty(JSON_PROPERTY_FUNCTION_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFunctionValue(Integer functionValue) {
        this.functionValue = functionValue;
    }


    /**
     * Return true if this LocomotiveFunctionCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LocomotiveFunctionCommand locomotiveFunctionCommand = (LocomotiveFunctionCommand) o;
        return Objects.equals(this.hashValue, locomotiveFunctionCommand.hashValue) &&
                Objects.equals(this.response, locomotiveFunctionCommand.response) &&
                Objects.equals(this.locId, locomotiveFunctionCommand.locId) &&
                Objects.equals(this.function, locomotiveFunctionCommand.function) &&
                Objects.equals(this.value, locomotiveFunctionCommand.value) &&
                Objects.equals(this.functionValue, locomotiveFunctionCommand.functionValue);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, locId, function, value, functionValue);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LocomotiveFunctionCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    locId: ").append(toIndentedString(locId)).append("\n");
        sb.append("    function: ").append(toIndentedString(function)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    functionValue: ").append(toIndentedString(functionValue)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

