/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * LocomotiveSpeedCommand
 */
@JsonPropertyOrder({
        LocomotiveSpeedCommand.JSON_PROPERTY_HASH_VALUE,
        LocomotiveSpeedCommand.JSON_PROPERTY_RESPONSE,
        LocomotiveSpeedCommand.JSON_PROPERTY_LOC_ID,
        LocomotiveSpeedCommand.JSON_PROPERTY_SPEED
})
public class LocomotiveSpeedCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_LOC_ID = "loc_id";
    public static final String JSON_PROPERTY_SPEED = "speed";
    private Integer hashValue;
    private Boolean response;
    private Integer locId;
    private Integer speed;

    public LocomotiveSpeedCommand() {
    }

    public LocomotiveSpeedCommand(Integer hashValue, Boolean response, Integer locId, Integer speed) {
        this.hashValue = hashValue;
        this.response = response;
        this.locId = locId;
        this.speed = speed;
    }

    public LocomotiveSpeedCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public LocomotiveSpeedCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public LocomotiveSpeedCommand locId(Integer locId) {
        this.locId = locId;
        return this;
    }

    /**
     * Get locId
     *
     * @return locId
     */
    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getLocId() {
        return locId;
    }


    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLocId(Integer locId) {
        this.locId = locId;
    }


    public LocomotiveSpeedCommand speed(Integer speed) {
        this.speed = speed;
        return this;
    }

    /**
     * Get speed
     *
     * @return speed
     */
    @JsonProperty(JSON_PROPERTY_SPEED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getSpeed() {
        return speed;
    }


    @JsonProperty(JSON_PROPERTY_SPEED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSpeed(Integer speed) {
        this.speed = speed;
    }


    /**
     * Return true if this LocomotiveSpeedCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LocomotiveSpeedCommand locomotiveSpeedCommand = (LocomotiveSpeedCommand) o;
        return Objects.equals(this.hashValue, locomotiveSpeedCommand.hashValue) &&
                Objects.equals(this.response, locomotiveSpeedCommand.response) &&
                Objects.equals(this.locId, locomotiveSpeedCommand.locId) &&
                Objects.equals(this.speed, locomotiveSpeedCommand.speed);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, locId, speed);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LocomotiveSpeedCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    locId: ").append(toIndentedString(locId)).append("\n");
        sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

