/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * LocomotiveCycleStopCommand
 */
@JsonPropertyOrder({
        LocomotiveCycleStopCommand.JSON_PROPERTY_HASH_VALUE,
        LocomotiveCycleStopCommand.JSON_PROPERTY_RESPONSE,
        LocomotiveCycleStopCommand.JSON_PROPERTY_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-21T20:30:51.693715200+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class LocomotiveCycleStopCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_ID = "id";
    @javax.annotation.Nonnull
    private Integer hashValue;
    @javax.annotation.Nonnull
    private Boolean response;
    @javax.annotation.Nonnull
    private Integer id;

    public LocomotiveCycleStopCommand() {
    }

    public LocomotiveCycleStopCommand hashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
    }


    public LocomotiveCycleStopCommand response(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
    }


    public LocomotiveCycleStopCommand id(@javax.annotation.Nonnull Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(@javax.annotation.Nonnull Integer id) {
        this.id = id;
    }


    /**
     * Return true if this LocomotiveCycleStopCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LocomotiveCycleStopCommand locomotiveCycleStopCommand = (LocomotiveCycleStopCommand) o;
        return Objects.equals(this.hashValue, locomotiveCycleStopCommand.hashValue) &&
                Objects.equals(this.response, locomotiveCycleStopCommand.response) &&
                Objects.equals(this.id, locomotiveCycleStopCommand.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, id);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LocomotiveCycleStopCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

