/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * LocomotiveDiscoveryCommand
 */
@JsonPropertyOrder({
        LocomotiveDiscoveryCommand.JSON_PROPERTY_HASH_VALUE,
        LocomotiveDiscoveryCommand.JSON_PROPERTY_RESPONSE,
        LocomotiveDiscoveryCommand.JSON_PROPERTY_LOC_ID,
        LocomotiveDiscoveryCommand.JSON_PROPERTY_PROTOCOL,
        LocomotiveDiscoveryCommand.JSON_PROPERTY_MFX_RANGE,
        LocomotiveDiscoveryCommand.JSON_PROPERTY_ASK_RATIO
})
public class LocomotiveDiscoveryCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_LOC_ID = "loc_id";
    public static final String JSON_PROPERTY_PROTOCOL = "protocol";
    public static final String JSON_PROPERTY_MFX_RANGE = "mfx_range";
    public static final String JSON_PROPERTY_ASK_RATIO = "ask_ratio";
    private Integer hashValue;
    private Boolean response;
    private Integer locId;
    private ProtocolSchema protocol;
    private Integer mfxRange;
    private Integer askRatio;

    public LocomotiveDiscoveryCommand() {
    }

    public LocomotiveDiscoveryCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public LocomotiveDiscoveryCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public LocomotiveDiscoveryCommand locId(Integer locId) {
        this.locId = locId;
        return this;
    }

    /**
     * Get locId
     *
     * @return locId
     */
    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getLocId() {
        return locId;
    }


    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLocId(Integer locId) {
        this.locId = locId;
    }


    public LocomotiveDiscoveryCommand protocol(ProtocolSchema protocol) {
        this.protocol = protocol;
        return this;
    }

    /**
     * Get protocol
     *
     * @return protocol
     */
    @JsonProperty(JSON_PROPERTY_PROTOCOL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public ProtocolSchema getProtocol() {
        return protocol;
    }


    @JsonProperty(JSON_PROPERTY_PROTOCOL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProtocol(ProtocolSchema protocol) {
        this.protocol = protocol;
    }


    public LocomotiveDiscoveryCommand mfxRange(Integer mfxRange) {
        this.mfxRange = mfxRange;
        return this;
    }

    /**
     * Get mfxRange
     *
     * @return mfxRange
     */
    @JsonProperty(JSON_PROPERTY_MFX_RANGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getMfxRange() {
        return mfxRange;
    }


    @JsonProperty(JSON_PROPERTY_MFX_RANGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMfxRange(Integer mfxRange) {
        this.mfxRange = mfxRange;
    }


    public LocomotiveDiscoveryCommand askRatio(Integer askRatio) {
        this.askRatio = askRatio;
        return this;
    }

    /**
     * Get askRatio
     *
     * @return askRatio
     */
    @JsonProperty(JSON_PROPERTY_ASK_RATIO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getAskRatio() {
        return askRatio;
    }


    @JsonProperty(JSON_PROPERTY_ASK_RATIO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAskRatio(Integer askRatio) {
        this.askRatio = askRatio;
    }


    /**
     * Return true if this LocomotiveDiscoveryCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LocomotiveDiscoveryCommand locomotiveDiscoveryCommand = (LocomotiveDiscoveryCommand) o;
        return Objects.equals(this.hashValue, locomotiveDiscoveryCommand.hashValue) &&
                Objects.equals(this.response, locomotiveDiscoveryCommand.response) &&
                Objects.equals(this.locId, locomotiveDiscoveryCommand.locId) &&
                Objects.equals(this.protocol, locomotiveDiscoveryCommand.protocol) &&
                Objects.equals(this.mfxRange, locomotiveDiscoveryCommand.mfxRange) &&
                Objects.equals(this.askRatio, locomotiveDiscoveryCommand.askRatio);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, locId, protocol, mfxRange, askRatio);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LocomotiveDiscoveryCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    locId: ").append(toIndentedString(locId)).append("\n");
        sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
        sb.append("    mfxRange: ").append(toIndentedString(mfxRange)).append("\n");
        sb.append("    askRatio: ").append(toIndentedString(askRatio)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

