/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * LocomotiveDirectionCommand
 */
@JsonPropertyOrder({
        LocomotiveDirectionCommand.JSON_PROPERTY_HASH_VALUE,
        LocomotiveDirectionCommand.JSON_PROPERTY_RESPONSE,
        LocomotiveDirectionCommand.JSON_PROPERTY_LOC_ID,
        LocomotiveDirectionCommand.JSON_PROPERTY_DIRECTION
})
public class LocomotiveDirectionCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_LOC_ID = "loc_id";
    public static final String JSON_PROPERTY_DIRECTION = "direction";
    private Integer hashValue;
    private Boolean response;
    private Integer locId;
    private String direction;

    public LocomotiveDirectionCommand() {
    }

    public LocomotiveDirectionCommand(Integer hashValue, Boolean response, Integer locId, String direction) {
        this.hashValue = hashValue;
        this.response = response;
        this.locId = locId;
        this.direction = direction;
    }

    public LocomotiveDirectionCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public LocomotiveDirectionCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public LocomotiveDirectionCommand locId(Integer locId) {
        this.locId = locId;
        return this;
    }

    /**
     * Get locId
     *
     * @return locId
     */
    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getLocId() {
        return locId;
    }


    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLocId(Integer locId) {
        this.locId = locId;
    }


    public LocomotiveDirectionCommand direction(String direction) {
        this.direction = direction;
        return this;
    }

    /**
     * Get direction
     *
     * @return direction
     */
    @JsonProperty(JSON_PROPERTY_DIRECTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDirection() {
        return direction;
    }


    @JsonProperty(JSON_PROPERTY_DIRECTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDirection(String direction) {
        this.direction = direction;
    }


    /**
     * Return true if this LocomotiveDirectionCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LocomotiveDirectionCommand locomotiveDirectionCommand = (LocomotiveDirectionCommand) o;
        return Objects.equals(this.hashValue, locomotiveDirectionCommand.hashValue) &&
                Objects.equals(this.response, locomotiveDirectionCommand.response) &&
                Objects.equals(this.locId, locomotiveDirectionCommand.locId) &&
                Objects.equals(this.direction, locomotiveDirectionCommand.direction);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, locId, direction);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LocomotiveDirectionCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    locId: ").append(toIndentedString(locId)).append("\n");
        sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

