/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * MfxBindCommand
 */
@JsonPropertyOrder({
        MfxBindCommand.JSON_PROPERTY_HASH_VALUE,
        MfxBindCommand.JSON_PROPERTY_RESPONSE,
        MfxBindCommand.JSON_PROPERTY_MFX_UID,
        MfxBindCommand.JSON_PROPERTY_MFX_SID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-21T20:30:51.693715200+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class MfxBindCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_MFX_UID = "mfx_uid";
    public static final String JSON_PROPERTY_MFX_SID = "mfx_sid";
    @javax.annotation.Nonnull
    private Integer hashValue;
    @javax.annotation.Nonnull
    private Boolean response;
    @javax.annotation.Nonnull
    private Integer mfxUid;
    @javax.annotation.Nonnull
    private Integer mfxSid;

    public MfxBindCommand() {
    }

    public MfxBindCommand hashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
    }


    public MfxBindCommand response(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
    }


    public MfxBindCommand mfxUid(@javax.annotation.Nonnull Integer mfxUid) {
        this.mfxUid = mfxUid;
        return this;
    }

    /**
     * Get mfxUid
     *
     * @return mfxUid
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_MFX_UID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getMfxUid() {
        return mfxUid;
    }


    @JsonProperty(JSON_PROPERTY_MFX_UID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setMfxUid(@javax.annotation.Nonnull Integer mfxUid) {
        this.mfxUid = mfxUid;
    }


    public MfxBindCommand mfxSid(@javax.annotation.Nonnull Integer mfxSid) {
        this.mfxSid = mfxSid;
        return this;
    }

    /**
     * Get mfxSid
     *
     * @return mfxSid
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_MFX_SID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getMfxSid() {
        return mfxSid;
    }


    @JsonProperty(JSON_PROPERTY_MFX_SID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setMfxSid(@javax.annotation.Nonnull Integer mfxSid) {
        this.mfxSid = mfxSid;
    }


    /**
     * Return true if this MfxBindCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MfxBindCommand mfxBindCommand = (MfxBindCommand) o;
        return Objects.equals(this.hashValue, mfxBindCommand.hashValue) &&
                Objects.equals(this.response, mfxBindCommand.response) &&
                Objects.equals(this.mfxUid, mfxBindCommand.mfxUid) &&
                Objects.equals(this.mfxSid, mfxBindCommand.mfxSid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, mfxUid, mfxSid);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MfxBindCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    mfxUid: ").append(toIndentedString(mfxUid)).append("\n");
        sb.append("    mfxSid: ").append(toIndentedString(mfxSid)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

