/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * ParticipantPingCommand
 */
@JsonPropertyOrder({
        ParticipantPingCommand.JSON_PROPERTY_HASH_VALUE,
        ParticipantPingCommand.JSON_PROPERTY_RESPONSE,
        ParticipantPingCommand.JSON_PROPERTY_SENDER_ID,
        ParticipantPingCommand.JSON_PROPERTY_SOFTWARE_VERSION,
        ParticipantPingCommand.JSON_PROPERTY_DEVICE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-21T20:30:51.693715200+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class ParticipantPingCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_SENDER_ID = "sender_id";
    public static final String JSON_PROPERTY_SOFTWARE_VERSION = "software_version";
    public static final String JSON_PROPERTY_DEVICE_ID = "device_id";
    @javax.annotation.Nonnull
    private Integer hashValue;
    @javax.annotation.Nonnull
    private Boolean response;
    @javax.annotation.Nullable
    private Integer senderId;
    @javax.annotation.Nullable
    private Integer softwareVersion;
    @javax.annotation.Nullable
    private Integer deviceId;

    public ParticipantPingCommand() {
    }

    public ParticipantPingCommand hashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
    }


    public ParticipantPingCommand response(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
    }


    public ParticipantPingCommand senderId(@javax.annotation.Nullable Integer senderId) {
        this.senderId = senderId;
        return this;
    }

    /**
     * Get senderId
     *
     * @return senderId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SENDER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getSenderId() {
        return senderId;
    }


    @JsonProperty(JSON_PROPERTY_SENDER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSenderId(@javax.annotation.Nullable Integer senderId) {
        this.senderId = senderId;
    }


    public ParticipantPingCommand softwareVersion(@javax.annotation.Nullable Integer softwareVersion) {
        this.softwareVersion = softwareVersion;
        return this;
    }

    /**
     * Get softwareVersion
     *
     * @return softwareVersion
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SOFTWARE_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getSoftwareVersion() {
        return softwareVersion;
    }


    @JsonProperty(JSON_PROPERTY_SOFTWARE_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSoftwareVersion(@javax.annotation.Nullable Integer softwareVersion) {
        this.softwareVersion = softwareVersion;
    }


    public ParticipantPingCommand deviceId(@javax.annotation.Nullable Integer deviceId) {
        this.deviceId = deviceId;
        return this;
    }

    /**
     * Get deviceId
     *
     * @return deviceId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getDeviceId() {
        return deviceId;
    }


    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeviceId(@javax.annotation.Nullable Integer deviceId) {
        this.deviceId = deviceId;
    }


    /**
     * Return true if this ParticipantPingCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ParticipantPingCommand participantPingCommand = (ParticipantPingCommand) o;
        return Objects.equals(this.hashValue, participantPingCommand.hashValue) &&
                Objects.equals(this.response, participantPingCommand.response) &&
                Objects.equals(this.senderId, participantPingCommand.senderId) &&
                Objects.equals(this.softwareVersion, participantPingCommand.softwareVersion) &&
                Objects.equals(this.deviceId, participantPingCommand.deviceId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, senderId, softwareVersion, deviceId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ParticipantPingCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
        sb.append("    softwareVersion: ").append(toIndentedString(softwareVersion)).append("\n");
        sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

