/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * S88EventCommand
 */
@JsonPropertyOrder({
        S88EventCommand.JSON_PROPERTY_HASH_VALUE,
        S88EventCommand.JSON_PROPERTY_RESPONSE,
        S88EventCommand.JSON_PROPERTY_DEVICE_ID,
        S88EventCommand.JSON_PROPERTY_CONTACT_ID,
        S88EventCommand.JSON_PROPERTY_PARAMETER,
        S88EventCommand.JSON_PROPERTY_STATE_OLD,
        S88EventCommand.JSON_PROPERTY_STATE_NEW,
        S88EventCommand.JSON_PROPERTY_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-21T20:30:51.693715200+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class S88EventCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_DEVICE_ID = "device_id";
    public static final String JSON_PROPERTY_CONTACT_ID = "contact_id";
    public static final String JSON_PROPERTY_PARAMETER = "parameter";
    public static final String JSON_PROPERTY_STATE_OLD = "state_old";
    public static final String JSON_PROPERTY_STATE_NEW = "state_new";
    public static final String JSON_PROPERTY_TIME = "time";
    @javax.annotation.Nonnull
    private Integer hashValue;
    @javax.annotation.Nonnull
    private Boolean response;
    @javax.annotation.Nonnull
    private Integer deviceId;
    @javax.annotation.Nonnull
    private Integer contactId;
    @javax.annotation.Nullable
    private Integer parameter;
    @javax.annotation.Nullable
    private Integer stateOld;
    @javax.annotation.Nullable
    private Integer stateNew;
    @javax.annotation.Nullable
    private Integer time;

    public S88EventCommand() {
    }

    public S88EventCommand hashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
    }


    public S88EventCommand response(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
    }


    public S88EventCommand deviceId(@javax.annotation.Nonnull Integer deviceId) {
        this.deviceId = deviceId;
        return this;
    }

    /**
     * Get deviceId
     *
     * @return deviceId
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getDeviceId() {
        return deviceId;
    }


    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDeviceId(@javax.annotation.Nonnull Integer deviceId) {
        this.deviceId = deviceId;
    }


    public S88EventCommand contactId(@javax.annotation.Nonnull Integer contactId) {
        this.contactId = contactId;
        return this;
    }

    /**
     * Get contactId
     *
     * @return contactId
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_CONTACT_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getContactId() {
        return contactId;
    }


    @JsonProperty(JSON_PROPERTY_CONTACT_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setContactId(@javax.annotation.Nonnull Integer contactId) {
        this.contactId = contactId;
    }


    public S88EventCommand parameter(@javax.annotation.Nullable Integer parameter) {
        this.parameter = parameter;
        return this;
    }

    /**
     * Get parameter
     *
     * @return parameter
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PARAMETER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getParameter() {
        return parameter;
    }


    @JsonProperty(JSON_PROPERTY_PARAMETER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setParameter(@javax.annotation.Nullable Integer parameter) {
        this.parameter = parameter;
    }


    public S88EventCommand stateOld(@javax.annotation.Nullable Integer stateOld) {
        this.stateOld = stateOld;
        return this;
    }

    /**
     * Get stateOld
     *
     * @return stateOld
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STATE_OLD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getStateOld() {
        return stateOld;
    }


    @JsonProperty(JSON_PROPERTY_STATE_OLD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStateOld(@javax.annotation.Nullable Integer stateOld) {
        this.stateOld = stateOld;
    }


    public S88EventCommand stateNew(@javax.annotation.Nullable Integer stateNew) {
        this.stateNew = stateNew;
        return this;
    }

    /**
     * Get stateNew
     *
     * @return stateNew
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STATE_NEW)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getStateNew() {
        return stateNew;
    }


    @JsonProperty(JSON_PROPERTY_STATE_NEW)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStateNew(@javax.annotation.Nullable Integer stateNew) {
        this.stateNew = stateNew;
    }


    public S88EventCommand time(@javax.annotation.Nullable Integer time) {
        this.time = time;
        return this;
    }

    /**
     * Get time
     *
     * @return time
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getTime() {
        return time;
    }


    @JsonProperty(JSON_PROPERTY_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTime(@javax.annotation.Nullable Integer time) {
        this.time = time;
    }


    /**
     * Return true if this S88EventCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        S88EventCommand s88EventCommand = (S88EventCommand) o;
        return Objects.equals(this.hashValue, s88EventCommand.hashValue) &&
                Objects.equals(this.response, s88EventCommand.response) &&
                Objects.equals(this.deviceId, s88EventCommand.deviceId) &&
                Objects.equals(this.contactId, s88EventCommand.contactId) &&
                Objects.equals(this.parameter, s88EventCommand.parameter) &&
                Objects.equals(this.stateOld, s88EventCommand.stateOld) &&
                Objects.equals(this.stateNew, s88EventCommand.stateNew) &&
                Objects.equals(this.time, s88EventCommand.time);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, deviceId, contactId, parameter, stateOld, stateNew, time);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class S88EventCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
        sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
        sb.append("    parameter: ").append(toIndentedString(parameter)).append("\n");
        sb.append("    stateOld: ").append(toIndentedString(stateOld)).append("\n");
        sb.append("    stateNew: ").append(toIndentedString(stateNew)).append("\n");
        sb.append("    time: ").append(toIndentedString(time)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

