/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * S88PollingCommand
 */
@JsonPropertyOrder({
        S88PollingCommand.JSON_PROPERTY_HASH_VALUE,
        S88PollingCommand.JSON_PROPERTY_RESPONSE,
        S88PollingCommand.JSON_PROPERTY_LOC_ID,
        S88PollingCommand.JSON_PROPERTY_MODULE_COUNT,
        S88PollingCommand.JSON_PROPERTY_MODULE,
        S88PollingCommand.JSON_PROPERTY_STATE
})
public class S88PollingCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_LOC_ID = "loc_id";
    public static final String JSON_PROPERTY_MODULE_COUNT = "module_count";
    public static final String JSON_PROPERTY_MODULE = "module";
    public static final String JSON_PROPERTY_STATE = "state";
    private Integer hashValue;
    private Boolean response;
    private Integer locId;
    private Integer moduleCount;
    private Integer module;
    private Integer state;

    public S88PollingCommand() {
    }

    public S88PollingCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public S88PollingCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public S88PollingCommand locId(Integer locId) {
        this.locId = locId;
        return this;
    }

    /**
     * Get locId
     *
     * @return locId
     */
    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getLocId() {
        return locId;
    }


    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLocId(Integer locId) {
        this.locId = locId;
    }


    public S88PollingCommand moduleCount(Integer moduleCount) {
        this.moduleCount = moduleCount;
        return this;
    }

    /**
     * Get moduleCount
     *
     * @return moduleCount
     */
    @JsonProperty(JSON_PROPERTY_MODULE_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getModuleCount() {
        return moduleCount;
    }


    @JsonProperty(JSON_PROPERTY_MODULE_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setModuleCount(Integer moduleCount) {
        this.moduleCount = moduleCount;
    }


    public S88PollingCommand module(Integer module) {
        this.module = module;
        return this;
    }

    /**
     * Get module
     *
     * @return module
     */
    @JsonProperty(JSON_PROPERTY_MODULE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getModule() {
        return module;
    }


    @JsonProperty(JSON_PROPERTY_MODULE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setModule(Integer module) {
        this.module = module;
    }


    public S88PollingCommand state(Integer state) {
        this.state = state;
        return this;
    }

    /**
     * Get state
     *
     * @return state
     */
    @JsonProperty(JSON_PROPERTY_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getState() {
        return state;
    }


    @JsonProperty(JSON_PROPERTY_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setState(Integer state) {
        this.state = state;
    }


    /**
     * Return true if this S88PollingCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        S88PollingCommand s88PollingCommand = (S88PollingCommand) o;
        return Objects.equals(this.hashValue, s88PollingCommand.hashValue) &&
                Objects.equals(this.response, s88PollingCommand.response) &&
                Objects.equals(this.locId, s88PollingCommand.locId) &&
                Objects.equals(this.moduleCount, s88PollingCommand.moduleCount) &&
                Objects.equals(this.module, s88PollingCommand.module) &&
                Objects.equals(this.state, s88PollingCommand.state);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, locId, moduleCount, module, state);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class S88PollingCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    locId: ").append(toIndentedString(locId)).append("\n");
        sb.append("    moduleCount: ").append(toIndentedString(moduleCount)).append("\n");
        sb.append("    module: ").append(toIndentedString(module)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

