/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * S88PollingCommand
 */
@JsonPropertyOrder({
        S88PollingCommand.JSON_PROPERTY_HASH_VALUE,
        S88PollingCommand.JSON_PROPERTY_RESPONSE,
        S88PollingCommand.JSON_PROPERTY_LOC_ID,
        S88PollingCommand.JSON_PROPERTY_MODULE_COUNT,
        S88PollingCommand.JSON_PROPERTY_MODULE,
        S88PollingCommand.JSON_PROPERTY_STATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-21T20:30:51.693715200+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class S88PollingCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_LOC_ID = "loc_id";
    public static final String JSON_PROPERTY_MODULE_COUNT = "module_count";
    public static final String JSON_PROPERTY_MODULE = "module";
    public static final String JSON_PROPERTY_STATE = "state";
    @javax.annotation.Nonnull
    private Integer hashValue;
    @javax.annotation.Nonnull
    private Boolean response;
    @javax.annotation.Nonnull
    private Integer locId;
    @javax.annotation.Nullable
    private Integer moduleCount;
    @javax.annotation.Nullable
    private Integer module;
    @javax.annotation.Nullable
    private Integer state;

    public S88PollingCommand() {
    }

    public S88PollingCommand hashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
    }


    public S88PollingCommand response(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
    }


    public S88PollingCommand locId(@javax.annotation.Nonnull Integer locId) {
        this.locId = locId;
        return this;
    }

    /**
     * Get locId
     *
     * @return locId
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getLocId() {
        return locId;
    }


    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLocId(@javax.annotation.Nonnull Integer locId) {
        this.locId = locId;
    }


    public S88PollingCommand moduleCount(@javax.annotation.Nullable Integer moduleCount) {
        this.moduleCount = moduleCount;
        return this;
    }

    /**
     * Get moduleCount
     *
     * @return moduleCount
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MODULE_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getModuleCount() {
        return moduleCount;
    }


    @JsonProperty(JSON_PROPERTY_MODULE_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setModuleCount(@javax.annotation.Nullable Integer moduleCount) {
        this.moduleCount = moduleCount;
    }


    public S88PollingCommand module(@javax.annotation.Nullable Integer module) {
        this.module = module;
        return this;
    }

    /**
     * Get module
     *
     * @return module
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MODULE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getModule() {
        return module;
    }


    @JsonProperty(JSON_PROPERTY_MODULE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setModule(@javax.annotation.Nullable Integer module) {
        this.module = module;
    }


    public S88PollingCommand state(@javax.annotation.Nullable Integer state) {
        this.state = state;
        return this;
    }

    /**
     * Get state
     *
     * @return state
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getState() {
        return state;
    }


    @JsonProperty(JSON_PROPERTY_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setState(@javax.annotation.Nullable Integer state) {
        this.state = state;
    }


    /**
     * Return true if this S88PollingCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        S88PollingCommand s88PollingCommand = (S88PollingCommand) o;
        return Objects.equals(this.hashValue, s88PollingCommand.hashValue) &&
                Objects.equals(this.response, s88PollingCommand.response) &&
                Objects.equals(this.locId, s88PollingCommand.locId) &&
                Objects.equals(this.moduleCount, s88PollingCommand.moduleCount) &&
                Objects.equals(this.module, s88PollingCommand.module) &&
                Objects.equals(this.state, s88PollingCommand.state);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, locId, moduleCount, module, state);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class S88PollingCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    locId: ").append(toIndentedString(locId)).append("\n");
        sb.append("    moduleCount: ").append(toIndentedString(moduleCount)).append("\n");
        sb.append("    module: ").append(toIndentedString(module)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

