/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * SetSystemIdentifierCommand
 */
@JsonPropertyOrder({
        SetSystemIdentifierCommand.JSON_PROPERTY_HASH_VALUE,
        SetSystemIdentifierCommand.JSON_PROPERTY_RESPONSE,
        SetSystemIdentifierCommand.JSON_PROPERTY_ID,
        SetSystemIdentifierCommand.JSON_PROPERTY_SYSTEM_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-21T20:30:51.693715200+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class SetSystemIdentifierCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_SYSTEM_ID = "system_id";
    @javax.annotation.Nonnull
    private Integer hashValue;
    @javax.annotation.Nonnull
    private Boolean response;
    @javax.annotation.Nonnull
    private Integer id;
    @javax.annotation.Nullable
    private Integer systemId;

    public SetSystemIdentifierCommand() {
    }

    public SetSystemIdentifierCommand hashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(@javax.annotation.Nonnull Integer hashValue) {
        this.hashValue = hashValue;
    }


    public SetSystemIdentifierCommand response(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(@javax.annotation.Nonnull Boolean response) {
        this.response = response;
    }


    public SetSystemIdentifierCommand id(@javax.annotation.Nonnull Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(@javax.annotation.Nonnull Integer id) {
        this.id = id;
    }


    public SetSystemIdentifierCommand systemId(@javax.annotation.Nullable Integer systemId) {
        this.systemId = systemId;
        return this;
    }

    /**
     * Get systemId
     *
     * @return systemId
     */
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SYSTEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getSystemId() {
        return systemId;
    }


    @JsonProperty(JSON_PROPERTY_SYSTEM_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSystemId(@javax.annotation.Nullable Integer systemId) {
        this.systemId = systemId;
    }


    /**
     * Return true if this SetSystemIdentifierCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SetSystemIdentifierCommand setSystemIdentifierCommand = (SetSystemIdentifierCommand) o;
        return Objects.equals(this.hashValue, setSystemIdentifierCommand.hashValue) &&
                Objects.equals(this.response, setSystemIdentifierCommand.response) &&
                Objects.equals(this.id, setSystemIdentifierCommand.id) &&
                Objects.equals(this.systemId, setSystemIdentifierCommand.systemId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, id, systemId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SetSystemIdentifierCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    systemId: ").append(toIndentedString(systemId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

