/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dhbw.modellbahn.adapter.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * SwitchingAccessoriesCommand
 */
@JsonPropertyOrder({
        SwitchingAccessoriesCommand.JSON_PROPERTY_HASH_VALUE,
        SwitchingAccessoriesCommand.JSON_PROPERTY_RESPONSE,
        SwitchingAccessoriesCommand.JSON_PROPERTY_LOC_ID,
        SwitchingAccessoriesCommand.JSON_PROPERTY_POSITION,
        SwitchingAccessoriesCommand.JSON_PROPERTY_POWER,
        SwitchingAccessoriesCommand.JSON_PROPERTY_VALUE
})
public class SwitchingAccessoriesCommand {
    public static final String JSON_PROPERTY_HASH_VALUE = "hash_value";
    public static final String JSON_PROPERTY_RESPONSE = "response";
    public static final String JSON_PROPERTY_LOC_ID = "loc_id";
    public static final String JSON_PROPERTY_POSITION = "position";
    public static final String JSON_PROPERTY_POWER = "power";
    public static final String JSON_PROPERTY_VALUE = "value";
    private Integer hashValue;
    private Boolean response;
    private Integer locId;
    private Integer position;
    private Integer power;
    private Integer value;

    public SwitchingAccessoriesCommand() {
    }

    public SwitchingAccessoriesCommand(Integer hashValue, Boolean response, Integer locId, Integer position, Integer power, Integer value) {
        this.hashValue = hashValue;
        this.response = response;
        this.locId = locId;
        this.position = position;
        this.power = power;
        this.value = value;
    }

    public SwitchingAccessoriesCommand hashValue(Integer hashValue) {
        this.hashValue = hashValue;
        return this;
    }

    /**
     * Get hashValue
     *
     * @return hashValue
     */
    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getHashValue() {
        return hashValue;
    }


    @JsonProperty(JSON_PROPERTY_HASH_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHashValue(Integer hashValue) {
        this.hashValue = hashValue;
    }


    public SwitchingAccessoriesCommand response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     */
    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Boolean getResponse() {
        return response;
    }


    @JsonProperty(JSON_PROPERTY_RESPONSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setResponse(Boolean response) {
        this.response = response;
    }


    public SwitchingAccessoriesCommand locId(Integer locId) {
        this.locId = locId;
        return this;
    }

    /**
     * Get locId
     *
     * @return locId
     */
    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getLocId() {
        return locId;
    }


    @JsonProperty(JSON_PROPERTY_LOC_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLocId(Integer locId) {
        this.locId = locId;
    }


    public SwitchingAccessoriesCommand position(Integer position) {
        this.position = position;
        return this;
    }

    /**
     * Get position
     *
     * @return position
     */
    @JsonProperty(JSON_PROPERTY_POSITION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getPosition() {
        return position;
    }


    @JsonProperty(JSON_PROPERTY_POSITION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPosition(Integer position) {
        this.position = position;
    }


    public SwitchingAccessoriesCommand power(Integer power) {
        this.power = power;
        return this;
    }

    /**
     * Get power
     *
     * @return power
     */
    @JsonProperty(JSON_PROPERTY_POWER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getPower() {
        return power;
    }


    @JsonProperty(JSON_PROPERTY_POWER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPower(Integer power) {
        this.power = power;
    }


    public SwitchingAccessoriesCommand value(Integer value) {
        this.value = value;
        return this;
    }

    /**
     * Get value
     *
     * @return value
     */
    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getValue() {
        return value;
    }


    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setValue(Integer value) {
        this.value = value;
    }


    /**
     * Return true if this SwitchingAccessoriesCommand object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SwitchingAccessoriesCommand switchingAccessoriesCommand = (SwitchingAccessoriesCommand) o;
        return Objects.equals(this.hashValue, switchingAccessoriesCommand.hashValue) &&
                Objects.equals(this.response, switchingAccessoriesCommand.response) &&
                Objects.equals(this.locId, switchingAccessoriesCommand.locId) &&
                Objects.equals(this.position, switchingAccessoriesCommand.position) &&
                Objects.equals(this.power, switchingAccessoriesCommand.power) &&
                Objects.equals(this.value, switchingAccessoriesCommand.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashValue, response, locId, position, power, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SwitchingAccessoriesCommand {\n");
        sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    locId: ").append(toIndentedString(locId)).append("\n");
        sb.append("    position: ").append(toIndentedString(position)).append("\n");
        sb.append("    power: ").append(toIndentedString(power)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}

